FROM php:8.1.6-apache
WORKDIR /var/www/html
COPY ./public-html/tarea4 tarea4
COPY ./public-html/tarea5 tarea5
COPY ./public-html/tarea7 tarea7
COPY ./public-html/tarea9 tarea9
COPY ./public-html/tareaDIW tareaDIW
